### PR TITLE
Add excel file with user stories and test cases

### PR DESCRIPTION
**Pull request by Sulfastic**
Hey, I've just created a file in which user stories along with tasks and test cases should be injected; please read Legend inside it, before using

### CODE REVIEW

**Comment by PiotrEredin** [comment]
How do we differentiate between manual test and automatic tests?

**Comment by Sulfastic** [comment]
Manual test should be made manually e.g.: click the button and check if it behaves correctly.
Automatic test e.g.: unit test should be launched automatically by a command or as a part of build process.

**Comment by PiotrEredin** [comment]
My question regarded the xls file, how do we differentiate manual from automatic in the file? Or don't we?

**Comment by Sulfastic** [comment]
I think that there can't be difference, I am not sure what can be tested automatically and what manually using the chosen framework

**Comment by PiotrEredin** [comment]
OK then, makes sense. We don't have to decide it now.

**Review by PiotrEredin — APPROVED** [review]

**Pull request merged**
